Setup and mobile first
jorgegoco/Portfolio pull request #1
Opened 2022-09-21 16:56 UTC by jorgegoco

-set up linters
-complete Readme file
-add images
-add html and css files

2022-09-21 19:48 UTC, tugsem requested changes
Hi @jorgegoco , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights ⭐ 
:white_check_mark: You used the right Github Flow.
:white_check_mark: Your PR messages are descriptive overall.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 19:48 UTC, tugsem commented on index.html
> +  <nav class="mobile-menu"><i class="fa fa-bars"></i></nav>
- [ ] Kindly use header tag mainly for site's title or logo (or both) and the main site navigation. Implement this after:
- The logo or title should be inserted into 'a' tag. This is for three reasons: convention, semantics, and user experience(UX).

2022-09-21 19:48 UTC, tugsem commented on assets/stylesheets/main.css
> +.header-mobile {
- [ ] Kindly use flexbox to layout the elements in the header section: logo(left) and the hamburger button(right). This gives us a lot of options to align all our elements, plus, it's responsive.

2022-09-21 19:48 UTC, tugsem commented on index.html
> +  </header>
- [ ] Please wrap these into `section` tag as it represents a generic standalone section of the document, so use it. To layout elements in the section, again use flexbox.

2022-09-21 19:48 UTC, tugsem commented on index.html
> +    </div>
- [ ] The list of icons should use a `ul` tag to group them, and `li` per icon; each icon has `a` link (a tag).

Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using href. Please use them.

2022-09-21 19:48 UTC, tugsem commented on index.html
> +      <a href="#"><img src="/assets/images/angellist.svg"></a>
- [ ] In order to display your assets in other browsers you need to use relative paths in your src attributes. Kindly add these:
```suggestion
      <a href="#"><img src="./assets/images/twitter.svg"></a>
      <a href="#"><img src="./assets/images/linkedin.svg"></a>
      <a href="#"><img src="./assets/images/medium.svg"></a>
      <a href="#"><img src="./assets/images/github.svg"></a>
      <a href="#"><img src="./assets/images/angellist.svg"></a>
```

2022-09-21 19:48 UTC, tugsem commented on assets/stylesheets/main.css
> +  background-image: url(/assets/images/header_mobile_background.png);
- [ ] Please use relative path before this background image url. It can't be seen in other browsers right now.

2022-09-22 08:05 UTC, sumairq approved these changes
### Hi @jorgegoco , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 08:12 UTC, merged